// Run with: mongosh <connection-string> --file migrate-customs.js
// Adds hsCode and customsDescription to all products

const updates = [
  { sku: 'SBZ-002', hsCode: '33049900', customsDescription: 'Sunscreen and sun protection cosmetic cream with SPF filter for skin care' },
  { sku: 'SBZ-003', hsCode: '33049900', customsDescription: 'Exfoliating and acne-control facial cleanser cosmetic preparation for skin care' },
  { sku: 'SBZ-004', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'SBZ-005', hsCode: '33049900', customsDescription: 'Facial toner cosmetic preparation for skin balancing, pore refining and skin care' },
  { sku: 'SBZ-007', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'SBZ-008', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'SBZ-016', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'UNC-001', hsCode: '33049900', customsDescription: 'Cosmetic facial sheet mask for skin treatment, hydration and brightening' },
  { sku: 'UNC-002', hsCode: '33049900', customsDescription: 'Cosmetic facial sheet mask for skin treatment, hydration and brightening' },
  { sku: 'UNC-003', hsCode: '33049900', customsDescription: 'Cosmetic facial sheet mask for skin treatment, hydration and brightening' },
  { sku: 'UNC-004', hsCode: '33049900', customsDescription: 'Cosmetic acne and blemish patch for skin treatment and care' },
  { sku: 'UNC-005', hsCode: '33049900', customsDescription: 'Brightening and discoloration correcting face serum cosmetic preparation for skin tone' },
  { sku: 'UNC-006', hsCode: '33049900', customsDescription: 'Sunscreen and sun protection cosmetic cream with SPF filter for skin care' },
  { sku: 'UNC-007', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'UNC-008', hsCode: '33049900', customsDescription: 'Facial toner cosmetic preparation for skin balancing, pore refining and skin care' },
  { sku: 'UNC-009', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'UNC-010', hsCode: '33049900', customsDescription: 'Blemish control and acne treatment face serum cosmetic preparation for skin care' },
  { sku: 'UNC-011', hsCode: '33049900', customsDescription: 'Sunscreen and sun protection cosmetic cream with SPF filter for skin care' },
  { sku: 'UNC-012', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'UNC-013', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'UNC-014', hsCode: '33049900', customsDescription: 'Cosmetic skincare kit set containing multiple face care preparations' },
  { sku: 'PSK-001', hsCode: '33049900', customsDescription: 'Face serum cosmetic preparation for skin care and treatment' },
  { sku: 'BLU-001', hsCode: '33049900', customsDescription: 'Cosmetic facial sheet mask for skin treatment, hydration and brightening' },
  { sku: 'BLU-002', hsCode: '33049900', customsDescription: 'Cosmetic facial sheet mask for skin treatment, hydration and brightening' },
  { sku: 'JOUF-001', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'JOUF-002', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'JOUF-003', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'JOUF-004', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'JOUF-005', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'JOUF-006', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'JOUF-007', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'JOUF-008', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'JOUF-009', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'JOUF-010', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'JOUF-011', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'JOUF-012', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'JOUF-013', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'JOUF-014', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'JOUF-015', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'JOUF-016', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'JOUF-017', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'JOUF-018', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'JOUF-019', hsCode: '34011100', customsDescription: 'Toilet soap bar for personal hygiene and skin cleansing, cosmetic use' },
  { sku: 'JOUF-020', hsCode: '34011100', customsDescription: 'Toilet soap bar for personal hygiene and skin cleansing, cosmetic use' },
  { sku: 'JOUF-021', hsCode: '34011100', customsDescription: 'Toilet soap bar for personal hygiene and skin cleansing, cosmetic use' },
  { sku: 'JOUF-022', hsCode: '34011100', customsDescription: 'Toilet soap bar for personal hygiene and skin cleansing, cosmetic use' },
  { sku: 'JOUF-023', hsCode: '34011100', customsDescription: 'Toilet soap bar for personal hygiene and skin cleansing, cosmetic use' },
  { sku: 'JOUF-024', hsCode: '34011100', customsDescription: 'Toilet soap bar for personal hygiene and skin cleansing, cosmetic use' },
  { sku: 'NECT-001', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'NECT-003', hsCode: '33049900', customsDescription: 'Foaming facial cleanser cosmetic preparation for face cleansing and skin care' },
  { sku: 'NECT-004', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'NECT-005', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'NECT-007', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'NECT-008', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'NECT-009', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'NECT-010', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'NECT-011', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'NECT-012', hsCode: '33049900', customsDescription: 'Facial toner cosmetic preparation for skin balancing, pore refining and skin care' },
  { sku: 'NECT-013', hsCode: '33049900', customsDescription: 'Face serum cosmetic preparation for skin care and treatment' },
  { sku: 'NECT-014', hsCode: '33049900', customsDescription: 'Sunscreen and sun protection cosmetic cream with SPF filter for skin care' },
  { sku: 'NECT-015', hsCode: '33049900', customsDescription: 'Brightening and discoloration correcting face serum cosmetic preparation for skin tone' },
  { sku: 'NECT-016', hsCode: '33049900', customsDescription: 'Snail mucin repair face serum and essence cosmetic preparation for skin healing' },
  { sku: 'NECT-017', hsCode: '33049900', customsDescription: 'Facial toner cosmetic preparation for skin balancing, pore refining and skin care' },
  { sku: 'NECT-018', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'NECT-019', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'NECT-020', hsCode: '33049900', customsDescription: 'Facial toner cosmetic preparation for skin balancing, pore refining and skin care' },
  { sku: 'BEHT-001', hsCode: '33049900', customsDescription: 'Gel facial cleanser cosmetic preparation for face cleansing and skin care' },
  { sku: 'BEHT-002', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'BEHT-003', hsCode: '33049900', customsDescription: 'Snail mucin repair face serum and essence cosmetic preparation for skin healing' },
  { sku: 'BEHT-004', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'PET-001', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'PET-002', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'PET-003', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'PET-004', hsCode: '33072900', customsDescription: 'Body and bath oil cosmetic preparation for skin moisturising and care' },
  { sku: 'PET-005', hsCode: '33072900', customsDescription: 'Body and bath oil cosmetic preparation for skin moisturising and care' },
  { sku: 'PET-006', hsCode: '33072900', customsDescription: 'Body and bath oil cosmetic preparation for skin moisturising and care' },
  { sku: 'PET-007', hsCode: '33072900', customsDescription: 'Body and bath oil cosmetic preparation for skin moisturising and care' },
  { sku: 'PET-008', hsCode: '33072900', customsDescription: 'Body sugar scrub cosmetic exfoliating preparation for body skin care' },
  { sku: 'PET-009', hsCode: '33072900', customsDescription: 'Body sugar scrub cosmetic exfoliating preparation for body skin care' },
  { sku: 'PET-010', hsCode: '33072900', customsDescription: 'Body sugar scrub cosmetic exfoliating preparation for body skin care' },
  { sku: 'PET-011', hsCode: '33054000', customsDescription: 'Hair masque and deep conditioning treatment, cosmetic hair care product' },
  { sku: 'PET-012', hsCode: '33052000', customsDescription: 'Hair conditioner and leave-in treatment, cosmetic hair care product' },
  { sku: 'PET-013', hsCode: '33051000', customsDescription: 'Shampoo for hair cleansing and care, cosmetic hair product' },
  { sku: 'PET-014', hsCode: '33057000', customsDescription: 'Hair oil for scalp and hair treatment, cosmetic hair care product' },
  { sku: 'PET-015', hsCode: '33057000', customsDescription: 'Hair oil for scalp and hair treatment, cosmetic hair care product' },
  { sku: 'PET-016', hsCode: '33051000', customsDescription: 'Shampoo for hair cleansing and care, cosmetic hair product' },
  { sku: 'PET-017', hsCode: '33052000', customsDescription: 'Hair conditioner and leave-in treatment, cosmetic hair care product' },
  { sku: 'PET-018', hsCode: '33052000', customsDescription: 'Hair conditioner and leave-in treatment, cosmetic hair care product' },
  { sku: 'PET-019', hsCode: '33051000', customsDescription: 'Shampoo for hair cleansing and care, cosmetic hair product' },
  { sku: 'PET-020', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'TBO-001', hsCode: '33049900', customsDescription: 'Vitamin C brightening face serum cosmetic preparation for skin care and hyperpigmentation treatment' },
  { sku: 'TBO-002', hsCode: '33049900', customsDescription: 'Niacinamide brightening and pore-refining face serum cosmetic preparation for skin care' },
  { sku: 'TBO-003', hsCode: '33049900', customsDescription: 'Hyaluronic acid hydrating face serum cosmetic preparation for skin moisture retention' },
  { sku: 'TBO-004', hsCode: '33049900', customsDescription: 'Exfoliating face serum with AHA/glycolic acid cosmetic preparation for skin resurfacing' },
  { sku: 'TBO-005', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'TBO-006', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'TBO-007', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'TBO-008', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'TBO-009', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'TBO-010', hsCode: '33049900', customsDescription: 'Micellar cleansing water cosmetic preparation for facial cleansing and makeup removal' },
  { sku: 'TBO-011', hsCode: '33049900', customsDescription: 'Facial toner cosmetic preparation for skin balancing, pore refining and skin care' },
  { sku: 'TBO-012', hsCode: '33049900', customsDescription: 'Salicylic acid acne-control face serum cosmetic preparation for blemish treatment' },
  { sku: 'TBO-013', hsCode: '33049900', customsDescription: 'Facial toner cosmetic preparation for skin balancing, pore refining and skin care' },
  { sku: 'TBO-014', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'TBO-015', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'TBO-016', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'TBO-017', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'TBO-018', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'BEAT-001', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'BEAT-002', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'BEAT-003', hsCode: '33049900', customsDescription: 'Retinol anti-ageing face serum cosmetic preparation for skin renewal and wrinkle reduction' },
  { sku: 'BEAT-004', hsCode: '33049900', customsDescription: 'Exfoliating face serum with AHA/glycolic acid cosmetic preparation for skin resurfacing' },
  { sku: 'BEAT-005', hsCode: '33049900', customsDescription: 'Salicylic acid acne-control face serum cosmetic preparation for blemish treatment' },
  { sku: 'BEAT-006', hsCode: '33049900', customsDescription: 'Caffeine energising face serum cosmetic preparation for skin firming and de-puffing' },
  { sku: 'BEAT-007', hsCode: '33049900', customsDescription: 'Ceramide barrier repair face serum cosmetic preparation for skin hydration' },
  { sku: 'BEAT-008', hsCode: '33049900', customsDescription: 'Peptide anti-ageing face serum cosmetic preparation for skin repair and renewal' },
  { sku: 'BEAT-009', hsCode: '33049900', customsDescription: 'Vitamin C brightening face serum cosmetic preparation for skin care and hyperpigmentation treatment' },
  { sku: 'BEAT-010', hsCode: '33049900', customsDescription: 'Collagen firming face serum cosmetic preparation for skin elasticity and anti-ageing' },
  { sku: 'BEAT-011', hsCode: '33049900', customsDescription: 'Face serum cosmetic preparation for skin care and treatment' },
  { sku: 'BEAT-012', hsCode: '33049900', customsDescription: 'Hyaluronic acid hydrating face serum cosmetic preparation for skin moisture retention' },
  { sku: 'BEAT-013', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'BEAT-014', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'BEAT-015', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'BEAT-016', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'BEAT-017', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'BEAT-018', hsCode: '33049900', customsDescription: 'Gel facial cleanser cosmetic preparation for face cleansing and skin care' },
  { sku: 'BEAT-019', hsCode: '33049900', customsDescription: 'Gel facial cleanser cosmetic preparation for face cleansing and skin care' },
  { sku: 'BEAT-020', hsCode: '33049900', customsDescription: 'Exfoliating and acne-control facial cleanser cosmetic preparation for skin care' },
  { sku: 'BEAT-021', hsCode: '33049900', customsDescription: 'Foaming facial cleanser cosmetic preparation for face cleansing and skin care' },
  { sku: 'BEAT-022', hsCode: '33049900', customsDescription: 'Niacinamide brightening and pore-refining face serum cosmetic preparation for skin care' },
  { sku: 'BEAT-023', hsCode: '33049900', customsDescription: 'Vitamin C brightening face serum cosmetic preparation for skin care and hyperpigmentation treatment' },
  { sku: 'BEAT-024', hsCode: '33049900', customsDescription: 'Exfoliating face serum with AHA/glycolic acid cosmetic preparation for skin resurfacing' },
  { sku: 'BEAT-025', hsCode: '33049900', customsDescription: 'Hyaluronic acid hydrating face serum cosmetic preparation for skin moisture retention' },
  { sku: 'BEAT-026', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'BEAT-027', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'BEAT-028', hsCode: '33049900', customsDescription: 'Sunscreen and sun protection cosmetic cream with SPF filter for skin care' },
  { sku: 'BEAT-029', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'JUN-001', hsCode: '33049900', customsDescription: 'Brightening and discoloration correcting face serum cosmetic preparation for skin tone' },
  { sku: 'JUN-002', hsCode: '33049900', customsDescription: 'Brightening and discoloration correcting face serum cosmetic preparation for skin tone' },
  { sku: 'JUN-003', hsCode: '33049900', customsDescription: 'Microbiome defense face serum cosmetic preparation for skin barrier protection' },
  { sku: 'JUN-004', hsCode: '33049900', customsDescription: 'Microbiome defense face serum cosmetic preparation for skin barrier protection' },
  { sku: 'JUN-005', hsCode: '33049900', customsDescription: 'Face serum cosmetic preparation for skin care and treatment' },
  { sku: 'JUN-006', hsCode: '33049900', customsDescription: 'Face serum cosmetic preparation for skin care and treatment' },
  { sku: 'TBO-019', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'TBO-020', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'SBZ-001', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'SBZ-010', hsCode: '33049900', customsDescription: 'Exfoliating face serum with AHA/glycolic acid cosmetic preparation for skin resurfacing' },
  { sku: 'SBZ-012', hsCode: '33049900', customsDescription: 'Face serum cosmetic preparation for skin care and treatment' },
  { sku: 'SBZ-014', hsCode: '33049900', customsDescription: 'Niacinamide brightening and pore-refining face serum cosmetic preparation for skin care' },
  { sku: 'SBZ-015', hsCode: '33049900', customsDescription: 'Retinol anti-ageing face serum cosmetic preparation for skin renewal and wrinkle reduction' },
  { sku: 'SBZ-011', hsCode: '33049900', customsDescription: 'Salicylic acid acne-control face serum cosmetic preparation for blemish treatment' },
  { sku: 'SBZ-013', hsCode: '33049900', customsDescription: 'Sunscreen and sun protection cosmetic cream with SPF filter for skin care' },
  { sku: 'SBZ-006', hsCode: '33049900', customsDescription: 'Vitamin C brightening face serum cosmetic preparation for skin care and hyperpigmentation treatment' },
  { sku: 'SBZ-009', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'BUYB-001', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'FRA-042', hsCode: '33030010', customsDescription: 'Eau de parfum spray, cosmetic fragrance product for personal use, unisex scent' },
  { sku: 'NECT-022', hsCode: '33072900', customsDescription: 'Body treatment cosmetic preparation for skin discoloration correction and care' },
  { sku: 'NECT-023', hsCode: '33049900', customsDescription: 'Brightening and discoloration correcting face serum cosmetic preparation for skin tone' },
  { sku: 'NECT-024', hsCode: '33049900', customsDescription: 'Azelaic acid brightening face serum cosmetic preparation for skin tone correction' },
  { sku: 'NECT-025', hsCode: '33049900', customsDescription: 'Niacinamide brightening and pore-refining face serum cosmetic preparation for skin care' },
  { sku: 'NECT-028', hsCode: '33049900', customsDescription: 'Exfoliating and acne-control facial cleanser cosmetic preparation for skin care' },
  { sku: 'OMAR-004', hsCode: '33041000', customsDescription: 'Lip gloss and lip oil cosmetic beauty product for lip color and care' },
  { sku: 'OMAR-005', hsCode: '33041000', customsDescription: 'Lip gloss and lip oil cosmetic beauty product for lip color and care' },
  { sku: 'OMAR-006', hsCode: '33041000', customsDescription: 'Lip gloss and lip oil cosmetic beauty product for lip color and care' },
  { sku: 'OMAR-007', hsCode: '33049900', customsDescription: 'Cosmetic face primer preparation for skin smoothing and makeup base' },
  { sku: 'OMAR-008', hsCode: '33041000', customsDescription: 'Lip gloss and lip oil cosmetic beauty product for lip color and care' },
  { sku: 'OMAR-009', hsCode: '33041000', customsDescription: 'Lip gloss and lip oil cosmetic beauty product for lip color and care' },
  { sku: 'OMAR-010', hsCode: '33041000', customsDescription: 'Lip gloss and lip oil cosmetic beauty product for lip color and care' },
  { sku: 'OMAR-011', hsCode: '33041000', customsDescription: 'Lip gloss and lip oil cosmetic beauty product for lip color and care' },
  { sku: 'TBO-021', hsCode: '33049900', customsDescription: 'Facial toner cosmetic preparation for skin balancing, pore refining and skin care' },
  { sku: 'TBO-022', hsCode: '33049900', customsDescription: 'Foaming facial cleanser cosmetic preparation for face cleansing and skin care' },
  { sku: 'TBO-023', hsCode: '33049900', customsDescription: 'Cosmetic acne and blemish patch for skin treatment and care' },
  { sku: 'TBO-024', hsCode: '33049900', customsDescription: 'Vitamin C brightening face serum cosmetic preparation for skin care and hyperpigmentation treatment' },
  { sku: 'TBO-025', hsCode: '33049900', customsDescription: 'Retinol anti-ageing face serum cosmetic preparation for skin renewal and wrinkle reduction' },
  { sku: 'TBO-026', hsCode: '33049900', customsDescription: 'Hyaluronic acid hydrating face serum cosmetic preparation for skin moisture retention' },
  { sku: 'TBO-027', hsCode: '33049900', customsDescription: 'Niacinamide brightening and pore-refining face serum cosmetic preparation for skin care' },
  { sku: 'TBO-028', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'TBO-030', hsCode: '33049900', customsDescription: 'Collagen firming face serum cosmetic preparation for skin elasticity and anti-ageing' },
  { sku: 'TBO-031', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'TBO-033', hsCode: '21069099', customsDescription: 'Dietary supplement in liquid/gel form, vitamin C, for human consumption' },
  { sku: 'TBO-034', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'TBO-035', hsCode: '33049900', customsDescription: 'Blemish control and acne treatment face serum cosmetic preparation for skin care' },
  { sku: 'TBO-036', hsCode: '33049900', customsDescription: 'Face serum cosmetic preparation for skin care and treatment' },
  { sku: 'TBO-037', hsCode: '33049900', customsDescription: 'Brightening and discoloration correcting face serum cosmetic preparation for skin tone' },
  { sku: 'TBO-038', hsCode: '33049900', customsDescription: 'Face serum cosmetic preparation for skin care and treatment' },
  { sku: 'TBO-039', hsCode: '33049900', customsDescription: 'Blemish control and acne treatment face serum cosmetic preparation for skin care' },
  { sku: 'TBO-040', hsCode: '33049900', customsDescription: 'Gel facial cleanser cosmetic preparation for face cleansing and skin care' },
  { sku: 'TBO-041', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'TBO-042', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'TBO-043', hsCode: '33049900', customsDescription: 'Gel facial cleanser cosmetic preparation for face cleansing and skin care' },
  { sku: 'TBO-044', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'TBO-045', hsCode: '33049900', customsDescription: 'Face lotion cosmetic preparation for daily facial skin hydration and care' },
  { sku: 'TBO-046', hsCode: '33049900', customsDescription: 'Facial toner cosmetic preparation for skin balancing, pore refining and skin care' },
  { sku: 'TBO-047', hsCode: '33049900', customsDescription: 'Face serum cosmetic preparation for skin care and treatment' },
  { sku: 'TBO-048', hsCode: '33049900', customsDescription: 'Brightening and discoloration correcting face serum cosmetic preparation for skin tone' },
  { sku: 'TBO-049', hsCode: '33049900', customsDescription: 'Hyaluronic acid hydrating face serum cosmetic preparation for skin moisture retention' },
  { sku: 'TBO-050', hsCode: '33049900', customsDescription: 'Face serum cosmetic preparation for skin care and treatment' },
  { sku: 'TBO-051', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'TBO-052', hsCode: '33049900', customsDescription: 'Facial mask and detoxifying skin treatment cosmetic preparation for skin care' },
  { sku: 'TBO-053', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'TBO-054', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'FRA-021', hsCode: '33030010', customsDescription: 'Eau de parfum spray, cosmetic fragrance product for personal use, women\'s scent' },
  { sku: 'OMAR-001', hsCode: '33049900', customsDescription: 'Cosmetic face primer preparation for skin smoothing and makeup base' },
  { sku: 'OMAR-002', hsCode: '33049900', customsDescription: 'Face serum cosmetic preparation for skin care and treatment' },
  { sku: 'OMAR-003', hsCode: '33049900', customsDescription: 'Cosmetic face primer preparation for skin smoothing and makeup base' },
  { sku: 'OMAR-012', hsCode: '33041000', customsDescription: 'Lip gloss and lip oil cosmetic beauty product for lip color and care' },
  { sku: 'OMAR-013', hsCode: '33041000', customsDescription: 'Lip gloss and lip oil cosmetic beauty product for lip color and care' },
  { sku: 'OMAR-014', hsCode: '33041000', customsDescription: 'Lip gloss and lip oil cosmetic beauty product for lip color and care' },
  { sku: 'OMAR-015', hsCode: '33041000', customsDescription: 'Lip gloss and lip oil cosmetic beauty product for lip color and care' },
  { sku: 'OMAR-016', hsCode: '33041000', customsDescription: 'Lip gloss and lip oil cosmetic beauty product for lip color and care' },
  { sku: 'OMAR-017', hsCode: '33041000', customsDescription: 'Lip gloss and lip oil cosmetic beauty product for lip color and care' },
  { sku: 'TBO-029', hsCode: '33049900', customsDescription: 'Vitamin C brightening face serum cosmetic preparation for skin care and hyperpigmentation treatment' },
  { sku: 'TBO-032', hsCode: '21069099', customsDescription: 'Dietary supplement in liquid/gel form, vitamin C, for human consumption' },
  { sku: 'FRA-052', hsCode: '33030010', customsDescription: 'Eau de parfum spray, cosmetic fragrance product for personal use, women\'s scent' },
  { sku: 'FRA-020', hsCode: '33030010', customsDescription: 'Eau de parfum spray, cosmetic fragrance product for personal use, women\'s scent' },
  { sku: 'BEAT-030', hsCode: '33049900', customsDescription: 'Foaming facial cleanser cosmetic preparation for face cleansing and skin care' },
  { sku: 'BEAT-031', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'BEAT-032', hsCode: '33072900', customsDescription: 'Body wash and shower gel cosmetic preparation for body cleansing and skin care' },
  { sku: 'BEAT-033', hsCode: '33072900', customsDescription: 'Body and bath oil cosmetic preparation for skin moisturising and care' },
  { sku: 'BEAT-034', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'TBO-055', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'TBO-056', hsCode: '33049900', customsDescription: 'Facial scrub cosmetic exfoliating preparation for skin care' },
  { sku: 'TBO-057', hsCode: '33049900', customsDescription: 'Vitamin C brightening face serum cosmetic preparation for skin care and hyperpigmentation treatment' },
  { sku: 'JUMI-001', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'JUMI-002', hsCode: '33049900', customsDescription: 'Brightening and discoloration correcting face serum cosmetic preparation for skin tone' },
  { sku: 'BEES-001', hsCode: '33049900', customsDescription: 'Cosmetic eye contour sheet mask for skin care and brightening' },
  { sku: 'BEES-002', hsCode: '33072000', customsDescription: 'Roll-on deodorant and antiperspirant cosmetic product for personal hygiene' },
  { sku: 'BEES-003', hsCode: '33072000', customsDescription: 'Roll-on deodorant and antiperspirant cosmetic product for personal hygiene' },
  { sku: 'BEES-004', hsCode: '33072000', customsDescription: 'Roll-on deodorant and antiperspirant cosmetic product for personal hygiene' },
  { sku: 'BEES-005', hsCode: '33072000', customsDescription: 'Roll-on deodorant and antiperspirant cosmetic product for personal hygiene' },
  { sku: 'BEES-006', hsCode: '33072000', customsDescription: 'Roll-on deodorant and antiperspirant cosmetic product for personal hygiene' },
  { sku: 'BEES-007', hsCode: '33072000', customsDescription: 'Roll-on deodorant and antiperspirant cosmetic product for personal hygiene' },
  { sku: 'BEES-008', hsCode: '33072000', customsDescription: 'Roll-on deodorant and antiperspirant cosmetic product for personal hygiene' },
  { sku: 'BEES-009', hsCode: '33072000', customsDescription: 'Roll-on deodorant and antiperspirant cosmetic product for personal hygiene' },
  { sku: 'BEES-010', hsCode: '33049900', customsDescription: 'Facial toner cosmetic preparation for skin balancing, pore refining and skin care' },
  { sku: 'BEES-011', hsCode: '33072000', customsDescription: 'Roll-on deodorant and antiperspirant cosmetic product for personal hygiene' },
  { sku: 'BEES-012', hsCode: '33049900', customsDescription: 'Sunscreen and sun protection cosmetic cream with SPF filter for skin care' },
  { sku: 'BEES-013', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'BEES-014', hsCode: '33049900', customsDescription: 'Cosmetic beauty and personal care preparation for skin care' },
  { sku: 'BEES-015', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'BEES-016', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'BEES-017', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'BEES-018', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'BEES-019', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'BEES-020', hsCode: '33049900', customsDescription: 'Facial mask and detoxifying skin treatment cosmetic preparation for skin care' },
  { sku: 'BEES-021', hsCode: '33049900', customsDescription: 'Facial mask and detoxifying skin treatment cosmetic preparation for skin care' },
  { sku: 'BEES-022', hsCode: '33049900', customsDescription: 'Facial scrub cosmetic exfoliating preparation for skin care' },
  { sku: 'BEES-023', hsCode: '33049900', customsDescription: 'Sunscreen and sun protection cosmetic cream with SPF filter for skin care' },
  { sku: 'BEES-024', hsCode: '33049900', customsDescription: 'Eye cream and eye contour cosmetic preparation for skin care' },
  { sku: 'BEES-025', hsCode: '33049900', customsDescription: 'Facial mask and detoxifying skin treatment cosmetic preparation for skin care' },
  { sku: 'BEES-026', hsCode: '33072000', customsDescription: 'Roll-on deodorant and antiperspirant cosmetic product for personal hygiene' },
  { sku: 'BEES-027', hsCode: '33072000', customsDescription: 'Roll-on deodorant and antiperspirant cosmetic product for personal hygiene' },
  { sku: 'BEES-028', hsCode: '33072000', customsDescription: 'Roll-on deodorant and antiperspirant cosmetic product for personal hygiene' },
  { sku: 'BEES-029', hsCode: '33049900', customsDescription: 'Micellar cleansing water cosmetic preparation for facial cleansing and makeup removal' },
  { sku: 'BEES-030', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'BEES-031', hsCode: '33049900', customsDescription: 'Facial toner cosmetic preparation for skin balancing, pore refining and skin care' },
  { sku: 'BEES-032', hsCode: '33049900', customsDescription: 'Eye cream and eye contour cosmetic preparation for skin care' },
  { sku: 'BEES-033', hsCode: '33049900', customsDescription: 'Brightening and discoloration correcting face serum cosmetic preparation for skin tone' },
  { sku: 'BEES-034', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'BEES-035', hsCode: '33072000', customsDescription: 'Roll-on deodorant and antiperspirant cosmetic product for personal hygiene' },
  { sku: 'BEES-036', hsCode: '33049900', customsDescription: 'Lip balm cosmetic preparation for lip moisturising and care' },
  { sku: 'BEES-037', hsCode: '33049900', customsDescription: 'Lip balm cosmetic preparation for lip moisturising and care' },
  { sku: 'TBO-058', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'BEAT-037', hsCode: '33049900', customsDescription: 'Face moisturiser and skin cream cosmetic preparation for facial skin hydration and care' },
  { sku: 'BEAT-038', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'NECT-029', hsCode: '33049900', customsDescription: 'Sunscreen and sun protection cosmetic cream with SPF filter for skin care' },
  { sku: 'NECT-030', hsCode: '33049900', customsDescription: 'Face lotion cosmetic preparation for daily facial skin hydration and care' },
  { sku: 'NECT-031', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'NECT-032', hsCode: '33049900', customsDescription: 'Foaming facial cleanser cosmetic preparation for face cleansing and skin care' },
  { sku: 'NECT-033', hsCode: '33049900', customsDescription: 'Eye cream and eye contour cosmetic preparation for skin care' },
  { sku: 'NECT-036', hsCode: '33049900', customsDescription: 'Skin treatment gel cosmetic preparation with active ingredients for skin care' },
  { sku: 'BEAT-039', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'NECT-006', hsCode: '33049900', customsDescription: 'Facial cleanser and face wash cosmetic preparation for skin cleansing and care' },
  { sku: 'NECT-002', hsCode: '33072900', customsDescription: 'Body lotion and moisturising cream cosmetic preparation for skin hydration and care' },
  { sku: 'NECT-034', hsCode: '33049900', customsDescription: 'Cosmetic facial sheet mask for skin treatment, hydration and brightening' },
  { sku: 'NECT-035', hsCode: '33049900', customsDescription: 'Cosmetic facial sheet mask for skin treatment, hydration and brightening' },
  { sku: 'GV-20000', hsCode: '99999999', customsDescription: 'Gift voucher / prepaid store credit card, non-monetary' },
  { sku: 'GV-50000', hsCode: '99999999', customsDescription: 'Gift voucher / prepaid store credit card, non-monetary' },
  { sku: 'GV-100000', hsCode: '99999999', customsDescription: 'Gift voucher / prepaid store credit card, non-monetary' }
];

let updated = 0;
for (const u of updates) {
  const r = db.products.updateOne(
    { sku: u.sku },
    { $set: { hsCode: u.hsCode, customsDescription: u.customsDescription } }
  );
  if (r.modifiedCount) updated++;
}
print(`Updated ${updated} of ${updates.length} products`);